# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-clj:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest
      - name: Run Tests
        run: clojure -M:test
  build-cljs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Run Tests
        run: clojure -M:test-cljs
